export { Hero } from './Hero'
export { Services } from './Services'
export { About } from './About'
export { Differentials } from './Differentials'
export { Testimonials } from './Testimonials'
export { Location } from './Location'
export { Instagram } from './Instagram'
export { FAQ } from './FAQ'
